import PropTypes from "prop-types";

const defaultProp = PropTypes.oneOf([PropTypes.string, PropTypes.number]);

export const uniStyles = {
  //bool
  absoluteFill: {
    styl: { position: "absolute", left: 0, right: 0, top: 0, bottom: 0 },
    type: PropTypes.bool
  },
  flexCenter: {
    styl: { alignItems: "center", justifyContent: "center" },
    type: PropTypes.bool
  },
  absolute: { stylKey: "position", type: PropTypes.bool },
  fixed: { stylKey: "position", type: PropTypes.bool },
  relative: { stylKey: "position", type: PropTypes.bool },
  sticky: { stylKey: "position", type: PropTypes.bool },
  //shorthand
  w: { stylKey: "width", type: defaultProp },
  h: { stylKey: "height", type: defaultProp },
  t: { stylKey: "top", type: defaultProp },
  r: { stylKey: "right", type: defaultProp },
  b: { stylKey: "bottom", type: defaultProp },
  l: { stylKey: "left", type: defaultProp },
  m: { stylKey: "margin", type: defaultProp },
  mt: { stylKey: "marginTop", type: defaultProp },
  mr: { stylKey: "marginRight", type: defaultProp },
  mb: { stylKey: "marginBottom", type: defaultProp },
  ml: { stylKey: "marginLeft", type: defaultProp },
  mx: { stylKey: "marginHorizontal", type: defaultProp },
  my: { stylKey: "marginVertical", type: defaultProp },
  p: { stylKey: "padding", type: defaultProp },
  pt: { stylKey: "paddingTop", type: defaultProp },
  pr: { stylKey: "paddingRight", type: defaultProp },
  pb: { stylKey: "paddingBottom", type: defaultProp },
  pl: { stylKey: "paddingLeft", type: defaultProp },
  px: { stylKey: "paddingHorizontal", type: defaultProp },
  py: { stylKey: "paddingVertical", type: defaultProp },
  bg: { stylKey: "backgroundColor", color: true, type: PropTypes.string },
  align: { stylKey: "alignItems", type: PropTypes.string },
  justify: { stylKey: "justifyContent", type: PropTypes.string },
  row: { stylKey: "flexDirection", type: PropTypes.bool },
  bw: { stylKey: "borderWidth" },
  bc: { stylKey: "borderColor", color: true },
  br: { stylKey: "borderRadius" }
};

export const styles = {
  ...uniStyles,
  //defaults
  width: {},
  fontSize: {},
  color: { color: true },
  fontFamily: {},
  textAlign: {},
  lineHeight: {},
  fontWeight: {},
  letterSpacing: {},
  display: {},
  maxWidth: {},
  minWidth: {},
  height: {},
  maxHeight: {},
  minHeight: {},
  verticalAlign: {},
  alignItems: {},
  alignContent: {},
  justifyItems: {},
  justifyContent: {},
  flexWrap: {},
  flexBasis: {},
  flexDirection: {},
  flex: {},
  justifySelf: {},
  alignSelf: {},
  order: {},
  gridGap: {},
  gridColumnGap: {},
  gridRowGap: {},
  gridColumn: {},
  gridRow: {},
  gridAutoFlow: {},
  gridAutoColumns: {},
  gridAutoRows: {},
  gridTemplateColumns: {},
  gridTemplateRows: {},
  gridTemplateAreas: {},
  gridArea: {},
  // borders
  border: {},
  borderTop: {},
  borderRight: {},
  borderBottom: {},
  borderLeft: {},
  borderWidth: {},
  borderTopWidth: {},
  borderRightWidth: {},
  borderBottomWidth: {},
  borderLeftWidth: {},
  borderColor: { color: true },
  borderTopColor: { color: true },
  borderRightColor: { color: true },
  borderBottomColor: { color: true },
  borderLeftColor: { color: true },
  borderRadius: {},
  boxShadow: {},
  opacity: {},
  overflow: {},
  background: { color: true },
  backgroundColor: { color: true },
  backgroundImage: {},
  backgroundPosition: {},
  backgroundRepeat: {},
  backgroundSize: {},
  position: {},
  zIndex: {},
  top: {},
  right: {},
  bottom: {},
  left: {}
};
